package EliteSet;

/**
 * Tracks which algorithm generated a solution
 * Used for analyzing the contribution of different components to the elite set
 */
public enum SolutionSource {
    /**
     * Solution generated by AILS main loop (perturbation + local search)
     */
    AILS,

    /**
     * Solution generated by Path Relinking between elite solutions
     */
    PATH_RELINKING,

    /**
     * Initial solution (constructive heuristic or warm start)
     */
    INITIAL;

    /**
     * Get short label for display
     */
    public String getLabel() {
        switch (this) {
            case AILS:
                return "AILS";
            case PATH_RELINKING:
                return "PR";
            case INITIAL:
                return "INIT";
            default:
                return "UNKNOWN";
        }
    }

    @Override
    public String toString() {
        return getLabel();
    }
}
